# Generated by Django 6.0.2 on 2026-05-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Cebolla, Tomate, Sal', max_length=100, verbose_name='Nombre del Ingrediente')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='notas',
            field=models.TextField(blank=True, help_text='Ej. Sin cebolla, bien cocido', null=True, verbose_name='Notas del cliente'),
        ),
        migrations.AddField(
            model_name='orden',
            name='es_para_llevar',
            field=models.BooleanField(default=False, help_text='Indica si el pedido es para llevar o para comer en el lugar', verbose_name='¿Es para llevar?'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='mesa',
            field=models.PositiveIntegerField(blank=True, help_text='Mesa que realiza el pedido (nulo si es para llevar)', null=True, verbose_name='Número de Mesa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, help_text='Ingredientes que conforman o pueden modificarse en el platillo', related_name='productos', to='menu.ingrediente', verbose_name='Ingredientes'),
        ),
    ]
