# Generated by Django 6.0.2 on 2026-02-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='para_llevar',
            field=models.BooleanField(default=False, help_text='El pedido es para llevar', verbose_name='Para llevar'),
        ),
    ]
