# Generated by Django 6.0.2 on 2026-05-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IVA (16%)'),
        ),
        migrations.AddField(
            model_name='orden',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal (Sin IVA)'),
        ),
    ]
