# Generated by Django 6.0.2 on 2026-05-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_orden_iva_orden_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', help_text='Seleccione el método de pago', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
