# Generated by Django 6.0.2 on 2026-05-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_ingrediente_detalleorden_notas_orden_es_para_llevar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='preparado',
            field=models.BooleanField(default=False, help_text='Indica si este platillo específico ya fue preparado por cocina', verbose_name='¿Preparado?'),
        ),
    ]
