# Generated by Django 6.0.2 on 2026-05-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_orden_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', help_text='Seleccione el método de pago', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
